/**
 * Maps a catalog item name (pipe form: "AWP | CERULEAN OZYMANDIAS") to the
 * URL of its icon under /public/items/. Falls back to null when the icon
 * isn't in the manifest (UI shows weapon/skin text instead).
 *
 * Manifest is built from the bot's catalog/icons/ directory by
 * scripts/build-icon-manifest.mjs. To regenerate, copy the latest icons into
 * public/items/ and re-run the script.
 */

const ICONS: Record<string, string> = {
  "AWP | 8-BALL": "AWP_8-Ball.png",
  "AWP | 9-BALL": "AWP_9-Ball.png",
  "AWP | ARCTIC RECON": "AWP_Arctic_Recon.png",
  "AWP | BEWITCHED": "AWP_Bewitched.png",
  "AWP | BOREALIS": "AWP_Borealis.png",
  "AWP | BROLY AWESOME.": "AWP_Broly_Awesome..png",
  "AWP | BUBBLEGUM": "AWP_Bubblegum.png",
  "AWP | CELTIC": "AWP_Celtic.png",
  "AWP | CERULEAN OZYMANDIAS": "AWP_Cerulean_Ozymandias.png",
  "AWP | CRIMSON OZYMANDIAS": "AWP_Crimson_Ozymandias.png",
  "AWP | DRIFTER": "AWP_Drifter.png",
  "AWP | DYNASTY": "AWP_Dynasty.png",
  "AWP | ELEMENTALIST": "AWP_Elementalist.png",
  "AWP | EMPYREUS": "AWP_Empyreus.png",
  "AWP | FANTASY": "AWP_Fantasy.png",
  "AWP | FOR HER": "AWP_For_Her.png",
  "AWP | FOR HIM": "AWP_For_Him.png",
  "AWP | FRIGIDUS": "AWP_Frigidus.png",
  "AWP | FRUTIGER AERO": "AWP_Frutiger_Aero.png",
  "AWP | HYSOID": "AWP_Hysoid.png",
  "AWP | INFERNUS": "AWP_Infernus.png",
  "AWP | INVERTED": "AWP_Inverted.png",
  "AWP | JEWEL": "AWP_Jewel.png",
  "AWP | NEW YEARS 2026": "AWP_New_Years_2026.png",
  "AWP | PEPPERMINT": "AWP_Peppermint.png",
  "AWP | RAINBOW RUNNER": "AWP_Rainbow_Runner.png",
  "AWP | RED SPIRAL": "AWP_Red_Spiral.png",
  "AWP | REX": "AWP_Rex.png",
  "AWP | SHOGUN": "AWP_Shogun.png",
  "AWP | SUNSET RUNNER": "AWP_Sunset_Runner.png",
  "AWP | TRUE INVERTED": "AWP_True_Inverted.png",
  "AWP | TRUE PINK": "AWP_True_Pink.png",
  "AWP | UMBR-ELEMENTALIST": "AWP_Umbr-Elementalist.png",
  "AWP | VANILLA": "AWP_Vanilla.png",
  "AWP | VHS": "AWP_VHS.png",
  "AWP | WHITE SPIRAL": "AWP_White_Spiral.png",
  "BAYONET | ADURITE": "Bayonet_Adurite.png",
  "BAYONET | AMETHYST": "Bayonet_Amethyst.png",
  "BAYONET | ANGELIC": "Bayonet_Angelic.png",
  "BAYONET | AURORA": "Bayonet_Aurora.png",
  "BAYONET | BAYONET OF DESTINY": "Bayonet_Bayonet_of_Destiny.png",
  "BAYONET | BLACK IRON": "Bayonet_Black_Iron.png",
  "BAYONET | BOMBASTIC": "Bayonet_Bombastic.png",
  "BAYONET | CANDY CORN": "Bayonet_Candy_Corn.png",
  "BAYONET | COOKIE": "Bayonet_Cookie.png",
  "BAYONET | CRIMSON WEB": "Bayonet_Crimson_Web.png",
  "BAYONET | CULTIST": "Bayonet_Cultist.png",
  "BAYONET | CUPID": "Bayonet_Cupid.png",
  "BAYONET | EMERALD": "Bayonet_Emerald.png",
  "BAYONET | HYPNO": "Bayonet_Hypno.png",
  "BAYONET | MALACHITE": "Bayonet_Malachite.png",
  "BAYONET | OG BLUESTEEL": "Bayonet_OG_Bluesteel.png",
  "BAYONET | ONYX": "Bayonet_Onyx.png",
  "BAYONET | PEPPERMINT": "Bayonet_Peppermint.png",
  "BAYONET | PROTOTYPE": "Bayonet_Prototype.png",
  "BAYONET | RUBY": "Bayonet_Ruby.png",
  "BAYONET | SAPPHIRE": "Bayonet_Sapphire.png",
  "BAYONET | SUNSET": "Bayonet_Sunset.png",
  "BAYONET | VAMPIRIC": "Bayonet_Vampiric.png",
  "BAYONET | VANILLA": "Bayonet_Vanilla.png",
  "BAYONET | WANWOOD": "Bayonet_Wanwood.png",
  "BAYONET | ZOMBIE SLAYER": "Bayonet_Zombie_Slayer.png",
  "BOMBLINE | KITCHEN": "BOMBLINE_Kitchen.png",
  "BOMBLINE | PIXEL": "BOMBLINE_Pixel.png",
  "BUTTERFLY | ADURITE": "Butterfly_Adurite.png",
  "BUTTERFLY | BLACK IRON": "Butterfly_Black_Iron.png",
  "BUTTERFLY | BLUE CAMO": "Butterfly_Blue_Camo.png",
  "BUTTERFLY | BOMBASTIC": "Butterfly_Bombastic.png",
  "BUTTERFLY | BUTTERFLY OF DESTINY": "Butterfly_Butterfly_of_Destiny.png",
  "BUTTERFLY | CHERRY": "Butterfly_Cherry.png",
  "BUTTERFLY | COOKIE": "Butterfly_Cookie.png",
  "BUTTERFLY | DAMASCUS": "Butterfly_Damascus.png",
  "BUTTERFLY | DARKSTEEL": "Butterfly_Darksteel.png",
  "BUTTERFLY | FROSTBITE": "Butterfly_Frostbite.png",
  "BUTTERFLY | MALACHITE": "Butterfly_Malachite.png",
  "BUTTERFLY | OG BLUESTEEL": "Butterfly_OG_Bluesteel.png",
  "BUTTERFLY | PEPPERMINT": "Butterfly_Peppermint.png",
  "BUTTERFLY | VANILLA": "Butterfly_Vanilla.png",
  "BUTTERFLY | VELVET": "Butterfly_Velvet.png",
  "BUTTERFLY | VENOM": "Butterfly_Venom.png",
  "BUTTERFLY | WANWOOD": "Butterfly_Wanwood.png",
  "CANDY CANE | BLUEBERRY": "Candy_Cane_Blueberry.png",
  "CANDY CANE | PEPPERMINT": "Candy_Cane_Peppermint.png",
  "CANDY CANE | TUTTI FRUTTI": "Candy_Cane_Tutti_Frutti.png",
  "CANDY CANE | WINTERGREEN": "Candy_Cane_Wintergreen.png",
  "CLASSIC | RAINBOW RETROSLOP": "Classic_Rainbow_Retroslop.png",
  "DEAGLE | CASE HARDENED": "Deagle_Case_Hardened.png",
  "DEAGLE | CELTIC": "Deagle_Celtic.png",
  "DEAGLE | CUPID": "Deagle_Cupid.png",
  "DEAGLE | FRUTIGER METRO": "Deagle_Frutiger_Metro.png",
  "DEAGLE | INVERTED": "Deagle_Inverted.png",
  "DEAGLE | RED ZONE": "Deagle_RED_ZONE.png",
  "DEAGLE | SNOWFLAKE": "Deagle_Snowflake.png",
  "DEAGLE | TIGER STRIPE": "Deagle_Tiger_Stripe.png",
  "DEAGLE | TRUE INVERTED": "Deagle_True_Inverted.png",
  "DEAGLE | VANILLA": "Deagle_Vanilla.png",
  "DEFAULT | ABYSS": "Default_Abyss.png",
  "DEFAULT | BLACK AND YELLOW": "Default_Black_and_Yellow.png",
  "DEFAULT | BLUESTEEL": "Default_Bluesteel.png",
  "DEFAULT | CAULDRON": "Default_Cauldron.png",
  "DEFAULT | CHERRY WOOD": "Default_Cherry_Wood.png",
  "DEFAULT | CRIME SCENE": "Default_Crime_Scene.png",
  "DEFAULT | CRIMSON CATSEYE": "Default_Crimson_Catseye.png",
  "DEFAULT | DANCE DANCE": "Default_Dance_Dance.png",
  "DEFAULT | DARK NET": "Default_Dark_Net.png",
  "DEFAULT | DEFAULT OF DESTINY": "Default_Default_of_Destiny.png",
  "DEFAULT | DISCO": "Default_Disco.png",
  "DEFAULT | ETHEREAL": "Default_Ethereal.png",
  "DEFAULT | FLAMES": "Default_Flames.png",
  "DEFAULT | FLEUR DE AMOUR": "Default_Fleur_De_Amour.png",
  "DEFAULT | FLEUR DE NOEL": "Default_Fleur_De_Noel.png",
  "DEFAULT | GLACIAL": "Default_Glacial.png",
  "DEFAULT | GREEN STREAM": "Default_Green_Stream.png",
  "DEFAULT | HEARTS": "Default_Hearts.png",
  "DEFAULT | INDUSTRIAL": "Default_Industrial.png",
  "DEFAULT | INVERTED": "Default_Inverted.png",
  "DEFAULT | LIGHTNING": "Default_Lightning.png",
  "DEFAULT | MONARCH": "Default_Monarch.png",
  "DEFAULT | MUMMY": "Default_Mummy.png",
  "DEFAULT | NAUGHTY PRESENT": "Default_Naughty_Present.png",
  "DEFAULT | NICE PRESENT": "Default_Nice_Present.png",
  "DEFAULT | PEPPERMINT": "Default_Peppermint.png",
  "DEFAULT | PINK CAMO": "Default_Pink_Camo.png",
  "DEFAULT | POLAROID": "Default_Polaroid.png",
  "DEFAULT | REFLECTANCE": "Default_Reflectance.png",
  "DEFAULT | REINDEER": "Default_Reindeer.png",
  "DEFAULT | RING OF FIRE": "Default_Ring_of_Fire.png",
  "DEFAULT | ROSE": "Default_Rose.png",
  "DEFAULT | ROSE GOLD": "Default_Rose_Gold.png",
  "DEFAULT | SNAKE SKIN": "Default_Snake_Skin.png",
  "DEFAULT | STALKER": "Default_Stalker.png",
  "DEFAULT | TIDAL": "Default_Tidal.png",
  "DEFAULT | TRIBAL": "Default_Tribal.png",
  "DEFAULT | TRUE BLACK": "Default_True_Black.png",
  "DEFAULT | TRUE INVERTED": "Default_True_Inverted.png",
  "DEFAULT | TRUE PINK": "Default_True_Pink.png",
  "DEFAULT | TRUE WHITE": "Default_True_White.png",
  "DEFAULT | VAMPIRE HUNTER": "Default_Vampire_Hunter.png",
  "DEFAULT | VELVET": "Default_Velvet.png",
  "DEFAULT | VIRIDIAN": "Default_Viridian.png",
  "DEFAULT | WANWOOD": "Default_Wanwood.png",
  "DEFAULT | WOOD": "Default_Wood.png",
  "DEFAULT | ZOMBIE": "Default_Zombie.png",
  "EXECUTIONER | ASCII WHITE": "Executioner_Ascii_White.png",
  "EXECUTIONER | CASE HARDENED": "Executioner_Case_Hardened.png",
  "EXECUTIONER | FROSTBITE": "Executioner_Frostbite.png",
  "HAMMER | GOLDEN HAMMER": "Hammer_Golden_Hammer.png",
  "INTERVENTION | ANGELIC": "Intervention_Angelic.png",
  "INTERVENTION | APEX": "Intervention_Apex.png",
  "INTERVENTION | BLACK KNIGHT": "Intervention_Black_Knight.png",
  "INTERVENTION | BLACK VALK": "Intervention_Black_Valk.png",
  "INTERVENTION | BLOSSOM": "Intervention_Blossom.png",
  "INTERVENTION | CODEC": "Intervention_Codec.png",
  "INTERVENTION | EVERGREEN WINTER": "Intervention_Evergreen_Winter.png",
  "INTERVENTION | FRUTIGER AERO": "Intervention_Frutiger_Aero.png",
  "INTERVENTION | GINGERBREAD": "Intervention_Gingerbread.png",
  "INTERVENTION | HEARTBREAK": "Intervention_Heartbreak.png",
  "INTERVENTION | INVERTED": "Intervention_Inverted.png",
  "INTERVENTION | LONELY STAR": "Intervention_Lonely_Star.png",
  "INTERVENTION | NEW YEARS 2026": "Intervention_New_Years_2026.png",
  "INTERVENTION | NORTH STAR": "Intervention_North_Star.png",
  "INTERVENTION | PEPPERMINT": "Intervention_Peppermint.png",
  "INTERVENTION | REAPER": "Intervention_Reaper.png",
  "INTERVENTION | TEST": "Intervention_Test.png",
  "INTERVENTION | TRUE INVERTED": "Intervention_True_Inverted.png",
  "INTERVENTION | TRUE PINK": "Intervention_True_Pink.png",
  "INTERVENTION | VALKYRIE": "Intervention_Valkyrie.png",
  "INTERVENTION | VANILLA": "Intervention_Vanilla.png",
  "INTERVENTION | VIPER": "Intervention_Viper.png",
  "KARAMBIT | ADURITE": "Karambit_Adurite.png",
  "KARAMBIT | AURORA": "Karambit_Aurora.png",
  "KARAMBIT | BLACK IRON": "Karambit_Black_Iron.png",
  "KARAMBIT | BOMBASTIC": "Karambit_Bombastic.png",
  "KARAMBIT | CASE HARDENED": "Karambit_Case_Hardened.png",
  "KARAMBIT | COOKIE": "Karambit_Cookie.png",
  "KARAMBIT | HI": "Karambit_Hi.png",
  "KARAMBIT | KARAMBIT OF DESTINY": "Karambit_Karambit_of_Destiny.png",
  "KARAMBIT | KOI": "Karambit_Koi.png",
  "KARAMBIT | MALACHITE": "Karambit_Malachite.png",
  "KARAMBIT | NEBULEUM": "Karambit_Nebuleum.png",
  "KARAMBIT | OG BLUESTEEL": "Karambit_OG_Bluesteel.png",
  "KARAMBIT | PEPPERMINT": "Karambit_Peppermint.png",
  "KARAMBIT | ROSE FADE": "Karambit_Rose_Fade.png",
  "KARAMBIT | SAKURA": "Karambit_Sakura.png",
  "KARAMBIT | SUNSET": "Karambit_Sunset.png",
  "KARAMBIT | TIGER": "Karambit_Tiger.png",
  "KARAMBIT | VANILLA": "Karambit_Vanilla.png",
  "KARAMBIT | VIPER": "Karambit_Viper.png",
  "KARAMBIT | WANWOOD": "Karambit_Wanwood.png",
  "KATANA | ADURITE": "Katana_Adurite.png",
  "KATANA | BLACK IRON": "Katana_Black_Iron.png",
  "KATANA | BLACKSTEEL": "Katana_Blacksteel.png",
  "KATANA | BOMBASTIC": "Katana_Bombastic.png",
  "KATANA | CHERRY": "Katana_Cherry.png",
  "KATANA | COOKIE": "Katana_Cookie.png",
  "KATANA | CRIMSON": "Katana_Crimson.png",
  "KATANA | DYNASTY": "Katana_Dynasty.png",
  "KATANA | FROSTBORN": "Katana_Frostborn.png",
  "KATANA | KATANA OF DESTINY": "Katana_Katana_of_Destiny.png",
  "KATANA | MALACHITE": "Katana_Malachite.png",
  "KATANA | MURAMASA": "Katana_Muramasa.png",
  "KATANA | NEBULEUM": "Katana_Nebuleum.png",
  "KATANA | OG BLUESTEEL": "Katana_OG_Bluesteel.png",
  "KATANA | OROCHI": "Katana_Orochi.png",
  "KATANA | PEPPERMINT": "Katana_Peppermint.png",
  "KATANA | SHOGUN": "Katana_Shogun.png",
  "KATANA | TRUE BLACK": "Katana_True_Black.png",
  "KATANA | TRUE WHITE": "Katana_True_White.png",
  "KATANA | VANILLA": "Katana_Vanilla.png",
  "KATANA | WANWOOD": "Katana_Wanwood.png",
  "PAN | GOLDEN PAN": "Pan_Golden_Pan.png",
  "RAILGUN XM1 | BLOCKOUT": "Railgun_XM1_Blockout.png",
  "SFO TH SWORD | DARKHEART": "SFoTH_Sword_Darkheart.png",
  "SFO TH SWORD | FIREBRAND": "SFoTH_Sword_Firebrand.png",
  "SFO TH SWORD | GHOSTWALKER": "SFoTH_Sword_Ghostwalker.png",
  "SFO TH SWORD | ICE DAGGER": "SFoTH_Sword_Ice_Dagger.png",
  "SFO TH SWORD | ILLUMINA": "SFoTH_Sword_Illumina.png",
  "SFO TH SWORD | LINKED SWORD": "SFoTH_Sword_Linked_Sword.png",
  "SFO TH SWORD | VENOMSHANK": "SFoTH_Sword_Venomshank.png",
  "SFO TH SWORD | WINDFORCE": "SFoTH_Sword_Windforce.png",
  "SHOTGUN | ASTRA": "Shotgun_Astra.png",
  "SHOTGUN | EPIC FACE": "Shotgun_Epic_Face.png",
  "SHOTGUN | GEMS ARE INFINITE": "Shotgun_Gems_are_Infinite.png",
  "SHOTGUN | INVERTED": "Shotgun_Inverted.png",
  "SHOTGUN | MLG": "Shotgun_MLG.png",
  "SHOTGUN | ROYAL": "Shotgun_Royal.png",
  "SHOTGUN | SHAMROCK": "Shotgun_Shamrock.png",
  "SHOTGUN | SHOTGUN OF DESTINY": "Shotgun_Shotgun_of_Destiny.png",
  "SHOTGUN | TRANSPARENT": "Shotgun_Transparent.png",
  "SHOTGUN | TRUE INVERTED": "Shotgun_True_Inverted.png",
  "SHOTGUN | VANILLA": "Shotgun_Vanilla.png",
  "SHOTGUN | WANWOOD": "Shotgun_Wanwood.png",
  "SURVIVOR | ADURITE": "Survivor_Adurite.png",
  "SURVIVOR | BLACK IRON": "Survivor_Black_Iron.png",
  "SURVIVOR | BLUESTEEL": "Survivor_Bluesteel.png",
  "SURVIVOR | BOMBASTIC": "Survivor_Bombastic.png",
  "SURVIVOR | COOKIE": "Survivor_Cookie.png",
  "SURVIVOR | HADES": "Survivor_Hades.png",
  "SURVIVOR | HEARTBREAK": "Survivor_Heartbreak.png",
  "SURVIVOR | MALACHITE": "Survivor_Malachite.png",
  "SURVIVOR | OG BLUESTEEL": "Survivor_OG_Bluesteel.png",
  "SURVIVOR | PEPPERMINT": "Survivor_Peppermint.png",
  "SURVIVOR | SURVIVOR OF DESTINY": "Survivor_Survivor_of_Destiny.png",
  "SURVIVOR | VANILLA": "Survivor_Vanilla.png",
  "SURVIVOR | WANWOOD": "Survivor_Wanwood.png",
  "SWORD | OG ILLUMINA": "Sword_OG_Illumina.png",
  "SWORD | OG LINKED SWORD": "Sword_OG_Linked_Sword.png",
  "SWORD | SCARY DOUG": "Sword_Scary_Doug.png",
  "VKS | BLOXY COLA": "VKS_Bloxy_Cola.png",
  "VKS | DISCO": "VKS_Disco.png",
  "VKS | INVERTED": "VKS_Inverted.png",
  "VKS | TRUE INVERTED": "VKS_True_Inverted.png",
  "VKS | VANILLA": "VKS_Vanilla.png",
  "VKS | WITCHES BREW": "VKS_Witches_Brew.png"
}

export function iconUrl(catalogName: string | null | undefined): string | null {
  if (!catalogName) return null
  const file = ICONS[catalogName.toUpperCase()]
  return file ? `/items/${file}` : null
}

export function hasIcon(catalogName: string | null | undefined): boolean {
  if (!catalogName) return false
  return Boolean(ICONS[catalogName.toUpperCase()])
}

export function iconCount(): number {
  return Object.keys(ICONS).length
}
